export const Colors = {
    background: '#F4F4F4',
    tint: '#FF4C4C',
    tabIconDefault: '#687076',
    tabIconSelected: '#FF4C4C',
    white: '#fff',
    black: '#333',
    darkGrey: '#666',
    lightGrey: '#999',
    softText: '#555',
  };

  export const LightColors = {
    background: '#d9d9d9',
    mainColor: '#070420',
    mainColorWithOpacity: '#04072026',
    white: '#',
    black: '#',
    notification: '#',
    darkGrey: '#bbbb',
    lightGrey: '#333',
    softText: '#',
    header: '#',
    loading: '#',
    loadingHighlight: '#',
    placeholderBackground: '#',
  };
  
  export const DarkColors = {
    background: '#070420',
    mainColor: '#d9d9d9',
    mainColorWithOpacity: '#D9D9D926', 
    tabIconDefault: '#',
    tabIconSelected: '#',
    white: '#',
    black: '#',
    notification: '#',
    darkGrey: '#333',
    lightGrey: '#bbbb',
    softText: '#',
    header: '#',
    loading: '#',
    loadingHighlight: '#',
    placeholderBackground: '#', 
  };