export const Colors = {
  background: '#F4F4F4',
  tint: '#FF4C4C',
  tabIconDefault: '#687076',
  tabIconSelected: '#FF4C4C',
  white: '#fff',
  black: '#333',
  darkGrey: '#666',
  lightGrey: '#999',
  softText: '#555',
};

export const LightColors = {
  background: '#d9d9d9',
  mainColor: '#070420',
  mainColorWithOpacity: '#04072026',
  button: '#040720cc',
  darkGrey: '#333',
  lightGrey: '#bbbb',
  tint: '#FF4C4C',
  black: '#000',
  white: '#fff',
  skeletonBase: '#E0E3E7',
  progressBarBackground : '#e0e0e0',
  progressBarFill: '#4A5568',

  green: '#00674F',
  mustard: '#BA8E23',
  cardBackground: '#bbbb',
  loading: '#',
  loadingHighlight: '#',
  placeholderBackground: '#',
};

export const DarkColors = {
  background: '#070420',
  mainColor: '#d9d9d9',
  mainColorWithOpacity: '#D9D9D926',
  button: '#d9d9d9cc',
  darkGrey: '#bbbb',
  lightGrey: '#333',
  tint: '#FF4C4C',
  black: '#fff',
  white: '#000',
  skeletonBase: '#2C344C',
  progressBarBackground : '#1A1A2E',
  progressBarFill: '#A5B4FC',

  tabIconDefault: '#',
  tabIconSelected: '#',
  green: '#20C09A',
  mustard: '#F6CF4C',
  cardBackground: '#D9D9D926',
  loading: '#',
  loadingHighlight: '#',
  placeholderBackground: '#',
};